# Generated by Django 2.2.2 on 2019-06-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="Enter the photo's source URL", max_length=150)),
                ('text', models.TextField(default='a', help_text='Enter the main body of the announcement', max_length=2500)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Enter the title of the announcement', max_length=200)),
                ('author', models.CharField(help_text='Enter the author of the announcement', max_length=100)),
                ('date', models.DateTimeField()),
                ('body', models.TextField(help_text='Enter the main body of the announcement', max_length=2000)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text="Enter the company's phone number", max_length=13)),
                ('email', models.EmailField(help_text="Enter the company's phone number", max_length=254)),
                ('address', models.CharField(help_text="Enter the company's address", max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the route's name", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="Enter the photo's source URL", max_length=150)),
                ('zone', models.CharField(choices=[('A', 'Zone A'), ('B', 'Zone B')], default='A', help_text='Enter A for local or B for intercity', max_length=1)),
                ('price_cat', models.CharField(choices=[('n', 'Normal Price'), ('r', 'Reduced Price')], default='n', help_text='Enter Normal or Reduced', max_length=1)),
                ('value', models.DecimalField(decimal_places=2, default='0.0', help_text='Enter the price of the ticket', max_digits=5)),
                ('customer', models.TextField(help_text='Enter the eligible social categories', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the stop's name", max_length=150)),
                ('zone', models.CharField(choices=[('a', 'Zone A'), ('b', 'Zone B')], default='a', help_text='Enter A for local or B for intercity', max_length=1)),
                ('number', models.IntegerField(help_text='Which stop is it? E.g Fisrt Stop is number 1 etc')),
                ('time_between', models.DurationField(help_text='Enter time between this stop and previous stop in ms')),
                ('route', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='patrasktel.Route')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('route', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrasktel.Route')),
            ],
            options={
                'unique_together': {('route', 'start_time')},
            },
        ),
    ]
